{
  vimUtils,
  fetchFromGitHub,
  pkgs,
  ...
}:
with pkgs.vimPlugins;
  [
    nvim-nio
    nvim-cmp
    cmp-nvim-lsp
    cmp-nvim-lua
    cmp-buffer
    cmp-path
    cmp-cmdline
    cmp_luasnip
    nvim-gdb
    gruvbox-nvim
    gitsigns-nvim
    vim-fugitive
    vim-repeat
    mini-icons
    none-ls-nvim
    conform-nvim
    vim-prettier
    plenary-nvim
    telescope-nvim
    telescope-fzf-native-nvim
    telescope-file-browser-nvim
    telescope-dap-nvim
    nvim-dap
    nvim-dap-virtual-text
    nvim-dap-view
    nvim-dap-ui
    nvim-dap-rr
    nvim-dap-python
    nvim-dap-lldb
    nvim-dap-go
    nvim-cursorline
    nvim-tree-lua
    nvim-surround
    nvim-navic
    nvim-autopairs
    nvim-ufo
    nvim-lspconfig
    nvim-lint
    typescript-tools-nvim
    harpoon2
    luasnip
    windsurf-vim
    undotree
    oil-nvim
    flash-nvim
    trouble-nvim
    indent-blankline-nvim
    nvim-ts-context-commentstring
    comment-nvim
    which-key-nvim
    lualine-nvim
  ]
  ++ [
    nvim-treesitter
    nvim-treesitter-textobjects
    nvim-treesitter-parsers.ada
    nvim-treesitter-parsers.agda
    nvim-treesitter-parsers.angular
    nvim-treesitter-parsers.apex
    nvim-treesitter-parsers.arduino
    nvim-treesitter-parsers.asm
    nvim-treesitter-parsers.astro
    nvim-treesitter-parsers.authzed
    nvim-treesitter-parsers.awk
    nvim-treesitter-parsers.bash
    nvim-treesitter-parsers.bass
    nvim-treesitter-parsers.beancount
    nvim-treesitter-parsers.bibtex
    nvim-treesitter-parsers.bicep
    nvim-treesitter-parsers.bitbake
    nvim-treesitter-parsers.blade
    nvim-treesitter-parsers.blueprint
    nvim-treesitter-parsers.bp
    nvim-treesitter-parsers.brightscript
    nvim-treesitter-parsers.c
    # nvim-treesitter-parsers.c3
    nvim-treesitter-parsers.c_sharp
    nvim-treesitter-parsers.caddy
    nvim-treesitter-parsers.cairo
    nvim-treesitter-parsers.capnp
    nvim-treesitter-parsers.chatito
    nvim-treesitter-parsers.circom
    nvim-treesitter-parsers.clojure
    nvim-treesitter-parsers.cmake
    nvim-treesitter-parsers.comment
    nvim-treesitter-parsers.commonlisp
    nvim-treesitter-parsers.cooklang
    nvim-treesitter-parsers.corn
    nvim-treesitter-parsers.cpon
    nvim-treesitter-parsers.cpp
    nvim-treesitter-parsers.css
    nvim-treesitter-parsers.csv
    nvim-treesitter-parsers.cuda
    nvim-treesitter-parsers.cue
    nvim-treesitter-parsers.cylc
    nvim-treesitter-parsers.d
    nvim-treesitter-parsers.dart
    nvim-treesitter-parsers.desktop
    nvim-treesitter-parsers.devicetree
    nvim-treesitter-parsers.dhall
    nvim-treesitter-parsers.diff
    nvim-treesitter-parsers.disassembly
    nvim-treesitter-parsers.djot
    nvim-treesitter-parsers.dockerfile
    nvim-treesitter-parsers.dot
    nvim-treesitter-parsers.doxygen
    nvim-treesitter-parsers.dtd
    nvim-treesitter-parsers.earthfile
    nvim-treesitter-parsers.ebnf
    nvim-treesitter-parsers.editorconfig
    nvim-treesitter-parsers.eds
    nvim-treesitter-parsers.eex
    nvim-treesitter-parsers.elixir
    nvim-treesitter-parsers.elm
    nvim-treesitter-parsers.elsa
    nvim-treesitter-parsers.elvish
    nvim-treesitter-parsers.embedded_template
    nvim-treesitter-parsers.enforce
    nvim-treesitter-parsers.erlang
    nvim-treesitter-parsers.facility
    nvim-treesitter-parsers.faust
    nvim-treesitter-parsers.fennel
    nvim-treesitter-parsers.fidl
    nvim-treesitter-parsers.firrtl
    nvim-treesitter-parsers.fish
    nvim-treesitter-parsers.foam
    nvim-treesitter-parsers.forth
    nvim-treesitter-parsers.fortran
    nvim-treesitter-parsers.fsh
    nvim-treesitter-parsers.fsharp
    nvim-treesitter-parsers.func
    nvim-treesitter-parsers.fusion
    nvim-treesitter-parsers.gap
    nvim-treesitter-parsers.gaptst
    nvim-treesitter-parsers.gdscript
    nvim-treesitter-parsers.gdshader
    nvim-treesitter-parsers.git_config
    nvim-treesitter-parsers.git_rebase
    nvim-treesitter-parsers.gitattributes
    nvim-treesitter-parsers.gitcommit
    nvim-treesitter-parsers.gitignore
    nvim-treesitter-parsers.gleam
    nvim-treesitter-parsers.glimmer
    nvim-treesitter-parsers.glimmer_javascript
    nvim-treesitter-parsers.glimmer_typescript
    nvim-treesitter-parsers.glsl
    nvim-treesitter-parsers.gn
    nvim-treesitter-parsers.gnuplot
    nvim-treesitter-parsers.go
    nvim-treesitter-parsers.goctl
    nvim-treesitter-parsers.godot_resource
    nvim-treesitter-parsers.gomod
    nvim-treesitter-parsers.gosum
    nvim-treesitter-parsers.gotmpl
    nvim-treesitter-parsers.gowork
    nvim-treesitter-parsers.gpg
    nvim-treesitter-parsers.graphql
    nvim-treesitter-parsers.gren
    nvim-treesitter-parsers.groovy
    nvim-treesitter-parsers.gstlaunch
    nvim-treesitter-parsers.hack
    nvim-treesitter-parsers.hare
    nvim-treesitter-parsers.haskell
    nvim-treesitter-parsers.haskell_persistent
    nvim-treesitter-parsers.hcl
    nvim-treesitter-parsers.heex
    nvim-treesitter-parsers.helm
    nvim-treesitter-parsers.hjson
    nvim-treesitter-parsers.hlsl
    nvim-treesitter-parsers.hlsplaylist
    nvim-treesitter-parsers.hocon
    nvim-treesitter-parsers.hoon
    nvim-treesitter-parsers.html
    nvim-treesitter-parsers.htmldjango
    nvim-treesitter-parsers.http
    nvim-treesitter-parsers.hurl
    nvim-treesitter-parsers.hyprlang
    nvim-treesitter-parsers.idl
    nvim-treesitter-parsers.idris
    nvim-treesitter-parsers.ini
    nvim-treesitter-parsers.inko
    nvim-treesitter-parsers.ispc
    nvim-treesitter-parsers.janet_simple
    nvim-treesitter-parsers.java
    nvim-treesitter-parsers.javadoc
    nvim-treesitter-parsers.javascript
    nvim-treesitter-parsers.jinja
    nvim-treesitter-parsers.jinja_inline
    nvim-treesitter-parsers.jq
    nvim-treesitter-parsers.jsdoc
    nvim-treesitter-parsers.json
    nvim-treesitter-parsers.json5
    nvim-treesitter-parsers.jsonc
    nvim-treesitter-parsers.jsonnet
    nvim-treesitter-parsers.julia
    nvim-treesitter-parsers.just
    nvim-treesitter-parsers.kcl
    nvim-treesitter-parsers.kconfig
    nvim-treesitter-parsers.kdl
    nvim-treesitter-parsers.kotlin
    nvim-treesitter-parsers.koto
    nvim-treesitter-parsers.kusto
    nvim-treesitter-parsers.lalrpop
    nvim-treesitter-parsers.latex
    nvim-treesitter-parsers.ledger
    nvim-treesitter-parsers.leo
    nvim-treesitter-parsers.linkerscript
    nvim-treesitter-parsers.liquid
    nvim-treesitter-parsers.liquidsoap
    nvim-treesitter-parsers.llvm
    nvim-treesitter-parsers.lua
    nvim-treesitter-parsers.luadoc
    nvim-treesitter-parsers.luap
    nvim-treesitter-parsers.luau
    nvim-treesitter-parsers.m68k
    nvim-treesitter-parsers.make
    nvim-treesitter-parsers.markdown
    nvim-treesitter-parsers.markdown_inline
    nvim-treesitter-parsers.matlab
    nvim-treesitter-parsers.menhir
    nvim-treesitter-parsers.mermaid
    nvim-treesitter-parsers.meson
    nvim-treesitter-parsers.mlir
    nvim-treesitter-parsers.muttrc
    nvim-treesitter-parsers.nasm
    nvim-treesitter-parsers.nginx
    nvim-treesitter-parsers.nickel
    nvim-treesitter-parsers.nim
    nvim-treesitter-parsers.nim_format_string
    nvim-treesitter-parsers.ninja
    nvim-treesitter-parsers.nix
    nvim-treesitter-parsers.nqc
    nvim-treesitter-parsers.nu
    nvim-treesitter-parsers.objc
    nvim-treesitter-parsers.objdump
    nvim-treesitter-parsers.ocaml
    nvim-treesitter-parsers.ocaml_interface
    nvim-treesitter-parsers.ocamllex
    nvim-treesitter-parsers.odin
    nvim-treesitter-parsers.pascal
    nvim-treesitter-parsers.passwd
    nvim-treesitter-parsers.pem
    nvim-treesitter-parsers.perl
    nvim-treesitter-parsers.php
    nvim-treesitter-parsers.php_only
    nvim-treesitter-parsers.phpdoc
    nvim-treesitter-parsers.pioasm
    nvim-treesitter-parsers.po
    nvim-treesitter-parsers.pod
    nvim-treesitter-parsers.poe_filter
    nvim-treesitter-parsers.pony
    nvim-treesitter-parsers.powershell
    nvim-treesitter-parsers.printf
    nvim-treesitter-parsers.prisma
    nvim-treesitter-parsers.problog
    nvim-treesitter-parsers.prolog
    nvim-treesitter-parsers.promql
    nvim-treesitter-parsers.properties
    nvim-treesitter-parsers.proto
    nvim-treesitter-parsers.prql
    nvim-treesitter-parsers.psv
    nvim-treesitter-parsers.pug
    nvim-treesitter-parsers.puppet
    nvim-treesitter-parsers.purescript
    nvim-treesitter-parsers.pymanifest
    nvim-treesitter-parsers.python
    nvim-treesitter-parsers.ql
    nvim-treesitter-parsers.qmldir
    nvim-treesitter-parsers.qmljs
    nvim-treesitter-parsers.query
    nvim-treesitter-parsers.r
    nvim-treesitter-parsers.racket
    nvim-treesitter-parsers.ralph
    nvim-treesitter-parsers.rasi
    nvim-treesitter-parsers.razor
    nvim-treesitter-parsers.rbs
    nvim-treesitter-parsers.re2c
    nvim-treesitter-parsers.readline
    nvim-treesitter-parsers.regex
    nvim-treesitter-parsers.rego
    nvim-treesitter-parsers.requirements
    nvim-treesitter-parsers.rescript
    nvim-treesitter-parsers.rnoweb
    nvim-treesitter-parsers.robot
    nvim-treesitter-parsers.robots
    nvim-treesitter-parsers.roc
    nvim-treesitter-parsers.ron
    nvim-treesitter-parsers.rst
    nvim-treesitter-parsers.ruby
    nvim-treesitter-parsers.runescript
    nvim-treesitter-parsers.rust
    nvim-treesitter-parsers.scala
    nvim-treesitter-parsers.scfg
    nvim-treesitter-parsers.scheme
    nvim-treesitter-parsers.scss
    nvim-treesitter-parsers.sflog
    nvim-treesitter-parsers.slang
    nvim-treesitter-parsers.slim
    nvim-treesitter-parsers.slint
    nvim-treesitter-parsers.smali
    nvim-treesitter-parsers.smithy
    nvim-treesitter-parsers.snakemake
    nvim-treesitter-parsers.solidity
    nvim-treesitter-parsers.soql
    nvim-treesitter-parsers.sosl
    nvim-treesitter-parsers.sourcepawn
    nvim-treesitter-parsers.sparql
    nvim-treesitter-parsers.sql
    nvim-treesitter-parsers.squirrel
    nvim-treesitter-parsers.ssh_config
    nvim-treesitter-parsers.starlark
    nvim-treesitter-parsers.strace
    nvim-treesitter-parsers.styled
    nvim-treesitter-parsers.supercollider
    nvim-treesitter-parsers.superhtml
    nvim-treesitter-parsers.surface
    nvim-treesitter-parsers.svelte
    nvim-treesitter-parsers.sway
    nvim-treesitter-parsers.swift
    nvim-treesitter-parsers.sxhkdrc
    nvim-treesitter-parsers.systemtap
    # nvim-treesitter-parsers.systemverilog
    nvim-treesitter-parsers.t32
    nvim-treesitter-parsers.tablegen
    nvim-treesitter-parsers.tact
    nvim-treesitter-parsers.tcl
    nvim-treesitter-parsers.teal
    nvim-treesitter-parsers.templ
    nvim-treesitter-parsers.tera
    nvim-treesitter-parsers.terraform
    nvim-treesitter-parsers.textproto
    nvim-treesitter-parsers.thrift
    nvim-treesitter-parsers.tiger
    nvim-treesitter-parsers.tlaplus
    nvim-treesitter-parsers.tmux
    nvim-treesitter-parsers.todotxt
    nvim-treesitter-parsers.toml
    nvim-treesitter-parsers.tsv
    nvim-treesitter-parsers.tsx
    nvim-treesitter-parsers.turtle
    nvim-treesitter-parsers.twig
    nvim-treesitter-parsers.typescript
    nvim-treesitter-parsers.typespec
    nvim-treesitter-parsers.typoscript
    nvim-treesitter-parsers.typst
    nvim-treesitter-parsers.udev
    nvim-treesitter-parsers.ungrammar
    nvim-treesitter-parsers.unison
    nvim-treesitter-parsers.usd
    nvim-treesitter-parsers.uxntal
    nvim-treesitter-parsers.v
    nvim-treesitter-parsers.vala
    nvim-treesitter-parsers.vento
    nvim-treesitter-parsers.vhdl
    nvim-treesitter-parsers.vhs
    nvim-treesitter-parsers.vim
    nvim-treesitter-parsers.vimdoc
    nvim-treesitter-parsers.vrl
    nvim-treesitter-parsers.vue
    nvim-treesitter-parsers.wgsl
    nvim-treesitter-parsers.wgsl_bevy
    nvim-treesitter-parsers.wing
    nvim-treesitter-parsers.wit
    nvim-treesitter-parsers.xcompose
    nvim-treesitter-parsers.xml
    nvim-treesitter-parsers.xresources
    nvim-treesitter-parsers.yaml
    nvim-treesitter-parsers.yang
    nvim-treesitter-parsers.yuck
    nvim-treesitter-parsers.zathurarc
    nvim-treesitter-parsers.zig
    nvim-treesitter-parsers.ziggy
    nvim-treesitter-parsers.ziggy_schema
  ]
  ++ [
    (vimUtils.buildVimPlugin {
      name = "coc-lit-html";
      src = fetchFromGitHub {
        owner = "fannheyward";
        repo = "coc-lit-html";
        rev = "0c942ee11b2f1309db8c7db2bbd65a07dc64fcf2";
        hash = "sha256-WGuNcD1uRUXbgJ6lm/DHcTnARF6GJ4qmycCDuWsOLpI=";
      };
    })
  ]
